### ISSUE TITLE
新创建项目UIImageToMat转换后channels()总是等于1

### ISSUE THREAD

**Issue by starLover** [muzipiao/OOB#6]
运行Demo时打印使用UIImageToMat转换后的colorMat.channels()一直为4，但是自己新建工程使用时一直为1，导致cvtColor灰度化图片时一直崩溃，请问是为什么?

**Comment by muzipiao** [comment]
你用的灰度图片吧？channel是1时为灰度图片，不需要转换，换一张彩色图片试试。

**Comment by starLover** [comment]
用的是Demo里面带的图片，名字为"apple"的那个

**Comment by starLover** [comment]
明白了，填充了透明像素
